services:
  onyx-mcp-server:
    image: docker.asm.co.il/onyx-mcp-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onyx-mcp-server
    ports:
      - "${HTTP_PORT:-3000}:3000"   # Maps the HTTP server port from .env or default 3000
    volumes:
      - ./logs:/app/logs            # Map logs directory
      - ./tmp:/app/tmp              # Map tmp directory
      - ./.env:/app/.env:ro         # Map .env file as read-only
    environment:
      # These environment variables will be overridden by .env file when mounted
      - ONYX_API_URL=${ONYX_API_URL:-http://localhost:8080/api}
      - ONYX_API_TOKEN=${ONYX_API_TOKEN:-your_api_token_here}
      - HTTP_PORT=${HTTP_PORT:-3000}
      - ONYX_DEFAULT_PERSONA_ID=${ONYX_DEFAULT_PERSONA_ID:-5}
      - DEBUG=${DEBUG:-false}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health", "||", "exit", "0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - onyx-network

networks:
  onyx-network:
    driver: bridge